//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocTruyen.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuong
    {
        public string Ma_Chuong { get; set; }
        public Nullable<int> So_Chuong { get; set; }
        public string Ten_Chuong { get; set; }
        public string NoiDung_Chuong { get; set; }
        public Nullable<int> Luotview_Chuong { get; set; }
        public Nullable<int> Ma_Truyen { get; set; }
    
        public virtual Truyen Truyen { get; set; }
    }
}
