//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocTruyen.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int Ma_DanhGia { get; set; }
        public string NoiDung_DanhGia { get; set; }
        public Nullable<int> Ma_Nguoidung { get; set; }
        public Nullable<int> Ma_Truyen { get; set; }
    
        public virtual Nguoidung Nguoidung { get; set; }
        public virtual Truyen Truyen { get; set; }
    }
}
