//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocTruyen.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int maNguoiDung { get; set; }
        public int maChucNang { get; set; }
        public string Ghi_Chu { get; set; }
    
        public virtual ChucNang ChucNang { get; set; }
        public virtual Nguoidung Nguoidung { get; set; }
    }
}
