//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDocTruyen.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Truyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Truyen()
        {
            this.Chuongs = new HashSet<Chuong>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public int Ma_Truyen { get; set; }
        public string Ten_Truyen { get; set; }
        public string HinhDaiDien { get; set; }
        public string MoTa_Truyen { get; set; }
        public Nullable<System.DateTime> NgayDang_Truyen { get; set; }
        public Nullable<int> Ma_Theloai { get; set; }
        public Nullable<int> Ma_Nguoidung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuong> Chuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual Nguoidung Nguoidung { get; set; }
        public virtual TheLoai TheLoai { get; set; }

        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpload { get; set; }
    }
}
